name: Docker Build and Push

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Verify Secrets Exist
      run: |
        echo "Username secret exists: ${{ secrets.DOCKER_HUB_USERNAME != '' }}"
        echo "Token secret exists: ${{ secrets.DOCKER_HUB_TOKEN != '' }}"

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Build and push backend
      run: |
        docker build -t bsanjuu/bmi-backend:latest ./BMICalc
        docker push bsanjuu/bmi-backend:latest

    - name: Login to Docker Hub
      run: |
        echo ${{ secrets.DOCKER_HUB_TOKEN }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin

    - name: Build and push frontend
      run: |
        docker build -t bsanjuu/bmi-frontend:latest ./bmi-frontend
        docker push bsanjuu/bmi-frontend:latest
